default_keybindings = false

[saved_state]
volume = 80

[keybindings]
######################################
# Song controls
######################################

##################
# Fast forward / rewind
##################
"b" = "seek -1000"
"f" = "seek +1000"
"Shift+b" = "seek -10000"
"Shift+f" = "seek +10000"

##################
# Play / pause
##################
" " = "playpause"
"Enter" = "play"
# "Shift+s" = "stop"

##################
# Track manipulation
##################
"p" = "previous"
"n" = "next"
"r" = "repeat"
"z" = "shuffle"
"Shift+d" = "delete"
"Shift+s" = "save"
# Open context menu
"Shift+o" = "open current"
"o" = "open selected"
"A" = "goto artist"
"a" = "goto album"


##################
# Queue
##################
# Add to queue
"Shift+q" = "queue"
# Move selected song up/down in the queue
"Shift+Down" = "shift down 1"
"Shift+Up" = "shift up 1"
"Shift+c" = "clear"

##################
# Sound
##################
"+" = "volup"
"-" = "voldown"

##################
# Moving
##################
"F1" = "focus queue"
"F2" = "focus search"
"F3" = "focus library"
# Go to the playing track
"." = "move playing"
# Navigation
"Down" = "move down 1"
"End" = "move bottom"
"Home" = "move top"
"Left" = "move left 1"
"PageDown" = "move down 5"
"PageUp" = "move up 5"
"Right" = "move right 1"
"Up" = "move up 1"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"q" = "back"

##################
# Sharing
##################
"Shift+x" = "share selected"
"x" = "share current"

##################
# Other
##################
"Ctrl+q" = "quit"
"?" = "help"
"Shift+u" = "update"

